version: '3.7'

services:
  lambda_teste-postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:12.8-alpine
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/data/db
      - PGTZ=GMT
    expose:
      - 5432
    volumes:
      - /data/postgres/${APP_NAME}:/data/db/:z
